import LocalizedStrings from 'react-native-localization';

export const strings = new LocalizedStrings({
 en:{
    slogan:'AUTOMATİON OF İNTERNSHİP            TRACKİNG',
    giris:'Login',
    frmaKyt:'Register of Company',
    kAdi:'User Name',
    parola:'Password',
    unutkan:'Forgot to Password',
    ogrListe:'The List Students',
    frmaListe:'The List Company',
    defter:'Notebook',
    basvuruislem:'Application Procedures',
    belgeler:'The Documents',
    firmalar:'The Companies',
    tarih:'Date:',
    konu:'Subject:',
    degerlendirmeF:'Evaluation Form',
    devletTKF:'state request contribution form',
    sigortaB:'insurance certificate',
    Onayla:'approve',
    Reddet:'reject',
    KurumAdi:'Company Name',
    FaaliyetAlani:'field of activity of the institution',
    adres:'Adress',
    Telefon:'Phone',
    eposta:'E-Mail',
    kayıt:'Register',
    ögrenciListesi:'student list',
    firmaOnayı:'company approval',
    stajDeft:'internships book',
    OgrenciBaşvuruları:'letter of application of students',
    ZorunlulukBelgOn:' certificate of obligation approval',
    baslangicTarih:'Start Date',
    bitisTarih:'End Date',
    pzt:'Monday',
    sali:'Tuesday',
    carsamba:'Wednesday.',
    persembe:'Thursday.',
    cuma:'Friday',
    cumartesi:'Saturday.',
    pazar:'Sunday',
    ocak:'January',
    subat:'February',
    mart:'March',
    nisan:'April',
    mayis:'May',
    haziran:'June ',
    temmuz:'July',
    agustos:'August',
    eylul:'September',
    ekim:'October',
    kasim:'November',
    aralik:'December',
    once:'Previous',
    sonra:'Next',
    indir:'Download',
    yukle:'Upload',
    frmaRed:'xxx',
    frmaOnay:'yyy'

 },
 tr:{
   slogan:'STAJ TAKİP OTOMASYONU',
   giris:'GİRİŞ YAP',
   frmaKyt:'FİRMA KAYIT OL',
   kAdi:'Kullanıcı Adı',
   parola:'Parola',
   unutkan:'Parolanızı mı Unuttunuz?',
   ogrListe:'Öğrenci Listesi',
   frmaListe:'Yeni Firma Başvuruları',
   defter:'Staj Defteri',
   basvuruislem:'Başvuru İşlemleri',
   belgeler:'Belgeler',
   firmalar:'Firmalar',
   tarih:'Tarih:',
   konu:'Konu:',
   degerlendirmeF:'Değerlendirme Formu',
   devletTKF:'Devlet Talep Katkı Formu',
   sigortaB:'Sigorta Belgesi',
   Onayla:'onayla',
   Reddet:'Reddet',
   KurumAdi:'KurumAdi',
   FaaliyetAlani:'Faaliyet Alani',
   adres:'Adres',
   Telefon:'telefon',
   eposta:'E posta',
   kayıt:'Kayıt Ol',
   ögrenciListesi:'Öğrenci Listesi',
   firmaOnayı:'Firma Onayları',
   stajDeft:'Staj Defteri',
   OgrenciBaşvuruları:'Öğrencinin Başvurusu',
   ZorunlulukBelgOn:'Zorunluluk Belgesi Onayı',
   baslangicTarih:'Başlangıç Tarihi',
   bitisTarih:'Bitiş Tarihi',
   pzt:'Pzt.',
   sali:'Salı',
   carsamba:'Çrş.',
   persembe:'Prş.',
   cuma:'Cuma',
   cumartesi:'Cts.',
   pazar:'Pzr.',
   ocak:'Ocak',
   subat:'Şubat',
   mart:'Mart',
   nisan:'Nisan',
   mayis:'Mayıs',
   haziran:'Haziran',
   temmuz:'Temmuz',
   agustos:'Ağustos',
   eylul:'Eylül',
   ekim:'Ekim',
   kasim:'Kasım',
   aralik:'Aralık',
   once:'Önceki',
   sonra:'Sonraki',
   indir:'İndir',
   yukle:'Yükle',
   frmaRed:'Reddedilen Firmalar',
   frmaOnay:'Onaylanan Firmalar'


 }
 
});